### ISSUE TITLE
Deleting cards

### ISSUE THREAD

**Issue by leothorp** [CravingCrates/AnkiCollab-Plugin#11]
Thanks for making AnkiCollab- it's been really useful. One thing I've noticed is that as far as I can tell, it doesn't seem possible to delete cards/suggest deletions as a deck author or maintainer. Is there currently a way to do this? if not, is it a planned feature?

**Comment by CravingCrates** [comment]
Yeah it's currently not possible to delete cards (or suggest their removal), but I will try to add that as a feature in the foreseeable future. It's on my to-do list but I can't give you an ETA.

**Comment by leothorp** [comment]
Good to hear, thank you.

**Comment by CravingCrates** [comment]
This has been implemented. Thanks for the suggestion @leothorp
