### ISSUE TITLE
Deleting subdecks

### ISSUE THREAD

**Issue by Cwwh** [CravingCrates/AnkiCollab-Plugin#15]
Great plugin, but is it possible to delete subdecks now? After renaming a subdeck, both subdecks with the old name and new name popped up. However, I couldn't delete the subdeck with the old name no matter what. It just keeps coming back after each update, and it seems to be uploaded to the ankicollab server. As the deck author, there is no such thing as subdeck with old name in my local deck, so I couldn't do anything with said subdeck via the local deck. 

On a side note, it was quite confusing for me to have so much decks in anki. Each set of deck uploaded to ankicollab forms a new set of deck, and just magically absorbs all cards from my local deck each time. Just a mild suggestion, maybe you could write down something in the maintainer/author guide regarding editing the local deck instead of the ankicollab deck and that its normal to have two decks at the same time :D

**Comment by CravingCrates** [comment]
Renaming or deleting subdecks is not yet supported (renaming it will get recognized as a "new" subdeck and hence duplicated).

Thanks for the second suggestion. I'll make sure to add that to the guides!

**Comment by Cwwh** [comment]
Oh ok thanks for the clarification. I'll look forward to the day that I can do that then
