### ISSUE TITLE
AnkiCollab preferences setting is overriding the default preference setting of Anki

### ISSUE THREAD

**Issue by makamto** [CravingCrates/AnkiCollab-Plugin#18]
After installed the add-on, I cannot open the default preference setting of Anki, not even with "cmd + ,"
Also, they are disappeared from the menu, 
<img width="449" alt="image" src="https://github.com/CravingCrates/AnkiCollab-Plugin/assets/143389271/964403cf-a24c-43f5-8d74-6caeeaee8984">

**Comment by CravingCrates** [comment]
yeah I've noticed that this happens for some people (apparently just on mac?).
Can you try and debug it yourself? I don't own any apple device so I can't reproduce the issue and it's not happening on linux or windows so I can't test it in a VM either.

Maybe you can figure out the exact line of code that's causing this unusual behavior. It ought to be somewhere around here:
https://github.com/CravingCrates/AnkiCollab-Plugin/blob/main/plugin_source/menu.py#L306

**Comment by CravingCrates** [comment]
@makamto Would you be able to test the latest fix by @KyleRego?

**Comment by makamto** [comment]
It should be fixed! Thank you all!
<img width="415" alt="image" src="https://github.com/CravingCrates/AnkiCollab-Plugin/assets/143389271/cc15dc06-277f-4b67-addd-d887ea9443e2">
<img width="178" alt="image" src="https://github.com/CravingCrates/AnkiCollab-Plugin/assets/143389271/496d9257-9bbb-45a3-bba8-50592de5de4f">
