### ISSUE TITLE
Google Drive integration not recognised

### ISSUE THREAD

**Issue by constantingoeldel** [CravingCrates/AnkiCollab-Plugin#21]
First of all, thanks for creating this tool, it'll be a lot of help for the upcoming exam season. 

# Issue

When setting up the Google Docs integration, everything works well but the settings are not persisted. On the deck management page, it will still say "Set Up" for Google Drive and when trying to upload existing deck media, I get the "No Google Drive Folder set for this deck" error message. 

The network request made when saving the integration setting returns a 200

![grafik](https://github.com/CravingCrates/AnkiCollab-Plugin/assets/67916925/c05f91e1-13ff-482c-929c-b09f2b9184ba)

What might be the issue? I'll be happy to help

## Debug info 

Request body

```json
{"deck":"video-hydrogen-jupiter-bulldog-april-venus","service_account":{"type":"service_account","project_id":"ankicollab-403511","private_key_id":"3cac9225e29dc05bfa2ec6f7e38f7ed81e1fdb46","private_key":"REDACTED","client_email":"anki-collab-drive-upload@ankicollab-403511.iam.gserviceaccount.com","client_id":"107120612039633696177","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/anki-collab-drive-upload%40ankicollab-403511.iam.gserviceaccount.com","universe_domain":"googleapis.com"},"folder_id":"19Uv7CbA2VSBGSRxULsyrQTu4uS_VIzcl"}
```

**Comment by CravingCrates** [comment]
Hey,
the deck management page does not change after uploading valid google drive data. (I'll put that on the todo tho!)
After seeing the "All set! You're ready" message on the website, you can go back to the anki desktop app and *pull the changes* (Check for Updates). This will download the google drive information you just entered on the website. it's not automated yet. (already on the todo list!)

Please check if checking for new content before trying to upload media files fixes it. If not, feel free to reach out to me on discord and send me your ankicollab config in anki in private. I'll gladly check it out.

**Comment by constantingoeldel** [comment]
I did check for updates, should have added that. I sent you the config on discord
