### ISSUE TITLE
[Bug?]media download just keeps going 

### ISSUE THREAD

**Issue by Mahgozar** [CravingCrates/AnkiCollab-Plugin#23]
whenever i try to download missing media from the anking deck, the downlaod goes way beyond the missing media count and i have to close it manually 
![image](https://github.com/CravingCrates/AnkiCollab-Plugin/assets/54596777/8c1fc3e6-8174-41c2-84b3-364af5855aae)

**Comment by she3o** [comment]
I don't have a testing platform. Can @CravingCrates see if the following in `plugin_source/google_drive_api.py` fixes this bug? 

```diff
     def download_selected_files_as_zip(self, file_names, local_folder_path, download_progress_cb=None):
-        files = []
         counter = 0
         for chunk in self.chunks(file_names, 50):  # break up file_names into chunks of 100
+            files = []
             if mw.progress.want_cancel():
                 break
             query = f"("

```
