### ISSUE TITLE
Can't edit or delete deck

### ISSUE THREAD

**Issue by Foxy-null** [CravingCrates/AnkiCollab-Plugin#24]
- [ ] "Save all changes" button not working. (but it reloads the edit screen)
- [ ] "Permanently delete this deck" button not working.

I really love your idea of this add-on.

Thank you for your development efforts. I will support you behind the scenes.

**Comment by CravingCrates** [comment]
Hey, I just tried both options and they work fine on my end. What browser are you using? Please try to delete your cache, make sure you're logged in on the website or try a different browser.
If the issue persists, feel free to reach out to me on discord.

**Comment by Foxy-null** [comment]
Thank you for the suggestion.
I'll contact you on your discord server soon.
