### ISSUE TITLE
Add-on fails to load

### ISSUE THREAD

**Issue by Isitsmd** [CravingCrates/AnkiCollab-Plugin#25]
![1710493288332276647533344502275](https://github.com/CravingCrates/AnkiCollab-Plugin/assets/81102543/e7d24944-e978-4b99-a6fe-199f7546a9e4)
Getting this problem after adding add-on in and 2.1.49 for Windows 8.

**Comment by CravingCrates** [comment]
Please update anki to a newer version. Your version is too old
