### ISSUE TITLE
Some images are not displayed in FAQ

### ISSUE THREAD

**Issue by w00000dy** [CravingCrates/AnkiCollab-Plugin#27]
The images of _How can I use Optional Tags on AnkiCollab?_ are not displayed in [faq.md](https://github.com/CravingCrates/AnkiCollab-Plugin/blob/main/faq.md).

**Comment by callebalik** [comment]
Same issue for me. As it's a bit hard to understand the tag structure from just the text updating these would help. 

Excerpts:

To create a new Optional Tag group, navigate to the AnkiCollab Website > Manage Decks > Select your Deck > Optional Tags: Show All.<br/>

This will bring you to a page like this:
<br/>
<img src="https://cdn.discordapp.com/attachments/1066468817351483502/1102317974511177858/RynkViW.png" width="50%">

[...]

Now you can go ahead and tag your notes to your liking and the subscribers will see a popup like this, when they subscribe to your deck:
<br />
<img src="https://cdn.discordapp.com/attachments/1066468817351483502/1102317974846718072/ZGS1WNr.png" width="50%">

**Comment by CravingCrates** [comment]
would appreciate a pull request that addresses this! Thank you!:)
