### ISSUE TITLE
Note Type changing

### ISSUE THREAD

**Issue by jwwood3** [CravingCrates/AnkiCollab-Plugin#28]
I'm using anki collab with my friend to help me learn portuguese. She has the deck and will add cards to it periodically so I can learn them.

Sometimes, when she goes to add new cards, the whole deck has been changed from the portuguese note type we made to a different type that has the same fields. Something like "portuguese-f26ed" with different letters and numbers each time.

This is mostly fine, but it means that it won't automatically show if she's making a duplicate card because the new card is a different note type than the existing one.

Is there something in the plugin that would do this, or some kind of setting in anki? I'd like all of the cards to keep the initial portuguese note type.
Thank you

**Comment by CravingCrates** [comment]
Hey yeah sorry that's a known bug. I'm not sure what's causing it tbh so I haven't figured out a way to fix it properly.. :/
